language: rust
rust:
  nightly

before_install:
  - apt-get install linux-libc-dev
script:
  - cargo test
  - cargo doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./target/doc/
  script:
  on:
    branch: master
