[package]
name = "neli"
version = "0.4.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[dependencies]
buffering = { git = "https://github.com/jbaublitz/buffering", version = "0.3.0" }
byteorder = "1.2"
libc = "0.2.43"
mio = "0.6"

[dependencies.tokio]
version = "0.1"
optional = true

[features]
default = []
stream = ["tokio"]
