[package]
name = "neli"
version = "0.4.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[dependencies]
byteorder = "1.2"
mio = "0.6"

[dependencies.libc]
git = "https://github.com/jbaublitz/libc"
branch = "nl_consts_pr"
version = "0.2.43"

[dependencies.tokio]
version = "0.1"
optional = true

[dependencies.buffering]
version = "0.3.2"
features = ["copy"]

[features]
default = []
stream = ["tokio"]
