[package]
name = "nl"
version = "0.1.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]

[build-dependencies]
cc = "*"
nl-constants-derive = { path = "nl-constants-derive" }

[dependencies]
byteorder = "1"
libc = "*"
