---
name: neli CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  clippy:
    strategy:
      matrix:
        task:
          - cargo clippy --all-targets -- -D warnings
          - (cd neli-proc-macros && cargo clippy --all-targets -- -D warnings)
        toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}
  glibc-checks:
    strategy:
      matrix:
        task:
          - cargo fmt -- --check
          - cargo build
          - cargo build --features=async
          - cargo build --all-features
          - RUST_TEST_THREADS=1 cargo test
          - RUST_TEST_THREADS=1 cargo test --features=async
          - RUST_TEST_THREADS=1 cargo test --all-features
          - (cd neli-proc-macros && cargo fmt -- --check)
          - (cd neli-proc-macros && cargo build)
          - (cd neli-proc-macros && RUST_TEST_THREADS=1 cargo test)
        toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}
  glibc-examples:
    strategy:
      matrix:
        toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Build examples
        run: cd examples && cargo build
      - name: Run getips
        run: ./examples/target/debug/getips
      - name: Run ctrl-list
        run: ./examples/target/debug/ctrl-list
      - name: Run route-list
        run: ./examples/target/debug/route-list
      - name: Run error_packet 
        run: ./examples/target/debug/error_packet
  musl-checks:
    strategy:
      matrix:
        task:
          - cargo build
          - cargo build --features=async
          - cargo build --all-features
          - RUST_TEST_THREADS=1 cargo test
          - RUST_TEST_THREADS=1 cargo test --features=async
          - RUST_TEST_THREADS=1 cargo test --all-features
        toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache gcc libc6-compat musl-dev
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}
  musl-examples:
    strategy:
      matrix:
        toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache gcc libc6-compat musl-dev
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Build examples
        run: cd examples && cargo build
      - name: Run getips
        run: ./examples/target/debug/getips
      - name: Run ctrl-list
        run: ./examples/target/debug/ctrl-list
      - name: Run route-list
        run: ./examples/target/debug/route-list
      - name: Run error_packet 
        run: ./examples/target/debug/error_packet
